### ISSUE TITLE
[YOM-565] fix bug

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-incomplete-files#6]
```
app.js:1 Uncaught Error: element or incompleteFilesContainer is null
    at isFileInView (plugin:incomplete-files:16508:11)
    at eval (plugin:incomplete-files:17101:16)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:713365)
    at t.onChange (app.js:1:703783)
    at e.trigger (app.js:1:610660)
    at e.<anonymous> (app.js:1:608471)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
```

<sub>[YOM-565](https://linear.app/yomaru/issue/YOM-565/fix-bug)</sub>

**Comment by HananoshikaYomaru** [comment]
this is done
